// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Filename     string
	FilePath     string
	EncryptedKey string
	FileSize     int64
	MimeType     string
	Checksum     string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	IpAddress *netip.Addr
	UserAgent pgtype.Text
}

type Share struct {
	ID           pgtype.UUID
	DocumentID   pgtype.UUID
	ShareToken   string
	ExpiresAt    pgtype.Timestamptz
	MaxAccess    pgtype.Int4
	AccessCount  pgtype.Int4
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	FullName     string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	IsActive     pgtype.Bool
}
